title: 软件定义网络（SDN）实验室
subtitle:
description:
author: sdnlab
language: zh-CN
TimeZone: Asia/Shanghai
Encoding: utf-8

BaseURL: https://sdn-lab.github.io
permalink: /:year/:month/:day/:title

lsi: true

#enable_coderay: true

#markdown: redcarpet
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

collections:
  sdn:
    output: true
#    permalink: /:collection/:name/
  nfv:
    output: true
#    permalink: /:collection/:name/
  controllers:
    output: true
#    permalink: /:collection/:path/
  switchs:
    output: true
#    permalink: /:collection/:path/
  sminulators:
    output: true
#    permalink: /:collection/:path/
  tools:
    output: true
#    permalink: /:collection/:name/
