title: 高级计算机网络（ANL）实验室
subtitle:
description:
author: AN-Lab
language: zh-CN
TimeZone: Asia/Shanghai
Encoding: utf-8

BaseURL: https://an-lab.github.io
permalink: /:year/:month/:day/:title

lsi: true

#enable_coderay: true

#markdown: redcarpet
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

collections:
  sdn:
    output: true
    permalink: /:collection/:name/
  nfv:
    output: true
    permalink: /:collection/:name/
  opendaylight:
    output: true
    directory: /controllers/:collection/
    permalink: /controllers/:collection/:path/
  floodlight:
    output: true
    directory: /controllers/:collection/
    permalink: /controllers/:collection/:path/
  open-vswitch:
    output: true
    directory: /switchs/:collection/
    permalink: /switchs/:collection/:path/
  mininet:
    output: true
    directory: /simulators/:collection/
    permalink: /simulators/:collection/:path/
  ns3:
    output: true
    directory: /simulators/:collection/
    permalink: /simulators/:collection/:path/
  tools:
    output: true
    directory: /network/:collection/
    permalink: /network/:collection/:name/
  knowledge-base: 
    output: true
    directory: /posts/
    permalink: /:collection/:name/
