title: 软件定义网络（SDN）实验室
subtitle:
description:
author: sdnlab
language: zh-CN
TimeZone: Asia/Shanghai
Encoding: utf-8

BaseURL: https://sdn-lab.github.io
permalink: /:year/:month/:day/:title

lsi: true

#enable_coderay: true

#markdown: redcarpet
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

collections:
  SDN:
    output: true
    permalink: /:collection/:path/
    title: "Software-Defined Networking"
    cTitle: 软件定义网络
  OFV:
    output: true
    title: "Network Function Virtualization"
    cTitle: 网络功能虚拟化
  Controller:
    title: Controller
    cTitle: 控制器
    collections:
      ODL:
        output: true
        title: OpenDayLight
        cTitle: OpenDayLight
      FloodLight:
        output: true
        title: FloodLight
        ctitle: FloodLight
  Switchs:
    title: Switchs
    cTitle: OF交换机
    collections:
      ovs:
        output: true
        title: "Open vSwitch"
        ctitle: "Open vSwitch"
  Sminulators:
    title: Sminulators
    cTitle: 仿真器
    collections:
      MiniNet:
        output: true
        title: "Mininet"
        ctitle: "Mininet"
      NS3:
        output: true
        title: "NS3"
        ctitle: "NS3"
